### ISSUE TITLE
sample code

### ISSUE THREAD

**Issue by gzbakku** [KizzyCode/crypto_api#1]
hey can you please provide any sample code to use symmetric aead cipher thanks buddy.

**Comment by KizzyCode** [comment]
Hey, this crate only defines an API. For a concrete implementation you can take a look at [`crypto_api_chachapoly`](https://crates.io/crates/crypto_api_chachapoly) for example. There you'd create a new AEAD instance using [`ChachaPolyIetf::aead_chipher()`](https://docs.rs/crypto_api_chachapoly/0.3.0/crypto_api_chachapoly/struct.ChachaPolyIetf.html).

Then you could seal some data using [`AeadCipher::seal_to`](https://docs.rs/crypto_api/0.2.2/crypto_api/cipher/trait.AeadCipher.html#tymethod.seal_to); e.g.:
```rust
// Get our key and nonce from somewhere
let key: &[u8] = unimplemented!("Some 32 byte key");
let nonce: &[u8] = unimplemented!("Some 12 byte nonce");

// Get our plaintext and additional data from somewhere
let plaintext: &[u8] = unimplemented!("Our plaintext");
let ad: &[u8] = unimplemented!("Our additional data");

// Create target buffer and seal the data
let mut buf = vec![0; plaintext.len() + 16]; // +16 bytes are necessary to hold the authentication tag
ChachaPolyIetf::aead_chipher().seal_to(&mut buf, plaintext, ad, key, nonce)?;
```
